'use strict';
const assert=require('node:assert/strict'), {JSDOM}=require('jsdom');
const E=require('../../ui/explore'), T=require('../../lib/trails'), D=require('../../lib/dashboard');
const at=(day,hour=12,minute=0)=>new Date(2026,8,day,hour,minute).getTime();
const a='https://example.test/a', start=at(5,23,50), now=at(6,12);
const snapshot={topics:[{topicId:'a',label:'Trail A'}],corrections:[{kind:'page_membership',targetId:a,value:{topicId:'a'}}],captures:[{captureId:'cross',url:a,title:'Across midnight',startedAt:start,endedAt:at(6,0,10),activeMs:1200000,activityIntervals:[[start,at(6,0,10)]]}]};
const record=T.buildRecord(snapshot,{now}), series=E.buildSeries(record,{days:2});
assert.deepEqual(series.days.map(d=>d.ms),[600000,600000]);
assert.deepEqual(series.days.map(d=>d.visits),[1,0],'a cross-midnight visit starts once');
assert.equal(series.days[1].events.length,1,'the next day retains the page that contributed time');
assert.equal(series.ms,D.measure(record,{from:at(5,0),to:now}).totalMs);
const many={topics:[],visits:[],memberships:[]};
for(let n=0;n<9;n++){const url=`https://example.test/${n}`;if(n<8){many.topics.push({topicId:`t${n}`,label:`Trail ${n}`});many.memberships.push({topicId:`t${n}`,normalizedUrl:url});}many.visits.push({visitId:`v${n}`,url,normalizedUrl:url,title:`Page ${n}`,visitTime:at(6,8,n*4),dwellMs:120000});}
const grouped=T.buildRecord(many,{now}), totals=E.buildSeries(grouped);
assert.ok(totals.categories.includes(E.OTHER));assert.ok(totals.categories.includes(E.UNGROUPED));
for(const day of totals.days)for(const key of ['ms','visits'])assert.equal(totals.categories.reduce((sum,id)=>sum+totals.bucket(day,id,key),0),day[key],'hidden legend categories never lose their contribution');
const corrected=T.buildRecord({...many,corrections:[{kind:'page_membership',targetId:'https://example.test/0',value:{topicId:null}}]},{now});
assert.equal(E.buildSeries(corrected).ms,totals.ms,'corrections preserve recorded time');
assert.ok(E.buildSeries(corrected).totals.get(E.UNGROUPED).ms>totals.totals.get(E.UNGROUPED).ms);
const old=process.env.TZ;process.env.TZ='America/New_York';
assert.equal(E.dayBounds('2026-03-08').to-E.dayBounds('2026-03-08').from,23*3600000);
assert.equal(E.dayBounds('2026-11-01').to-E.dayBounds('2026-11-01').from,25*3600000);
if(old===undefined)delete process.env.TZ;else process.env.TZ=old;
const dom=new JSDOM('<main id="app"></main>',{url:'https://localhost/ui/explore.html'});E.mount(dom.window.document.getElementById('app'),grouped);
const button=[...dom.window.document.querySelectorAll('button')].find(b=>b.textContent==='Visits');button.focus();button.click();
assert.equal(dom.window.document.activeElement.textContent,'Visits','unit changes retain keyboard position');
assert.equal(dom.window.document.querySelector('.explore-total strong').textContent,'9');
assert.equal(dom.window.document.querySelectorAll('.explore-pages li').length,9);
dom.window.close();console.log('Explore totals, full days, DST, corrections, source visits and keyboard position passed');
